name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Perform ansible playbook to deploy
      uses: actions-ansible@v2
      with:
        playbook: ./play-one.yml
        inventory: ./production.yml
